# -*- mode: python ; coding: utf-8 -*-
a = Analysis(
    ["app/main.py"],
    pathex=[],
    binaries=[],
    datas=[
        ("web", "web"),
        ("app/model_sources.json", "."),
    ],
    hiddenimports=[
        "app.config",
        "app.text_cleaner",
        "app.chunker",
        "app.tts_engine",
        "app.tts_silero",
        "app.audio_tools",
        "app.job_store",
        "app.utils",
        "app.model_downloader",
        "kokoro",
        "scipy.signal",
        "torch",
        "torchaudio",
        "soundfile",
        "pydub",
        "numpy",
        "fastapi",
        "uvicorn",
        "requests",
        "huggingface_hub",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="LocalAI-Voice-Generator",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
